---
name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: "0 7 * * 0"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build image according to Dockerfile.
      run: docker build -t docker-ansible .

    - name: Run the recently created image.
      run: docker run --privileged --name test-docker-ansible -v /sys/fs/cgroup:/sys/fs/cgroup:ro -d docker-ansible

    - name: Verify if Ansible is working.
      run: docker exec --tty test-docker-ansible ansible --version

  release:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub.
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push image to Docker Hub.
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: Dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ github.repository }}:latest
